### ISSUE TITLE
Resize window

### ISSUE THREAD

**Issue by leotada** [Epihaius/panda3dstudio#1]
Could resize or maximize window.

**Comment by Epihaius** [comment]
The ability to resize/maximize the window will be implemented as soon as I can use tobspr's [LUI](https://github.com/tobspr/LUI) for the 2D GUI.

Currently I am using wxPython for the GUI and it has already been very difficult for me to make it work as I want it to (under Linux it still doesn't). So I hope you understand that I would rather not extend the functionality of the GUI using wxPython any further, but that I prefer to wait until I can switch to LUI, which should be much easier to work with.

Right now, the specific problems with resizing are:
- the toolbars and side panel wouldn't automatically stretch along with the window (their sizes are hard-coded; I should use Sizers but I already had some problems with those and I don't feel like spending/wasting more time on that);
- for selecting objects in the Panda viewport, I use a special "picking camera" which needs a specific field of view that depends on the resolution of the viewport in order to allow the user to easily click on thin lines (for selecting edges) and on pixels (for selecting vertices). It even seems to depend on what graphics device and/or drivers are being used, so I need to find some way to make it user-configurable.

My apologies for the inconvenience, but it will take some time to get these things fixed.

**Comment by leotada** [comment]
I tested on Ubuntu 16.04 x64 and works. Ok, I'm looking forward to see with LUI.

**Comment by Epihaius** [comment]
Finally, after almost 2 years, this issue is fixed :) !

My apologies for the long wait, but it took a complete overhaul of the GUI (which is now pure-Panda instead of depending on wxPython) to make this possible.
