### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by berylliumquestion** [Epihaius/panda3dstudio#10]
Which license would this be released under? BSD? An MIT license? GPL? ...WTFPL? : P Anyway, I'd like to know.

**Comment by Epihaius** [comment]
Yeah, I've been wondering about that myself. Probably best to adopt the modified BSD license, as this is what Panda3D also uses.

For "copyright holder", I would just use Epihaius instead of my real name, unless someone can convince me to do otherwise.

If anyone has any thoughts on this, it would be appreciated, as I find this entire licensing business rather annoying, lol.
