### ISSUE TITLE
compat with double precision Panda3D builds

### ISSUE THREAD

**Issue by pmp-p** [Epihaius/panda3dstudio#5]
when panda3d is built with ```--override STDFLOAT_DOUBLE=1```
some operations will fail like
```
.add_data3f( Vec3 )
.add_data4f( Vec4 )
```
maybe can be rewritten as  .add_data3f( *V ) / .add_data3f( *V )

**Comment by Epihaius** [comment]
Hmm, could you perhaps report this issue at the panda3d repository as well?
It might be more useful if this could be fixed in Panda itself (after all, there might be more cases affected by it). If it's not possible, then I'll try the fix you suggested.

**Comment by rdb** [comment]
This is not a Panda bug, at first glance; you should use `add_data3` when you are passing in a `Vec3`/`LVector3`, and only use `add_data3f` when passing in a `Vec3F`/`LVector3f`.

**Comment by Epihaius** [comment]
Are you really sure about that? This seems to be at the very least an inconsistency in Panda; if using `add_data3f` is wrong when passing in a `Vec3`/`LVector3`, shouldn't doing so always throw an error, regardless of how Panda was built? I don't see how invalid code like this could become perfectly acceptable for a build created without that `-override STDFLOAT_DOUBLE=1` parameter.

Furthermore, when I look up `Vec3` and `LVector3` in the API reference, it tells me that both are merely typedefs for `LVector3f`. Indeed, when I print out a value defined as `Vec3` or `LVector3`, I get a `LVector3f` value.
In fact, for a future version of Panda where backwards compatibility becomes less important, wouldn't it be worth considering simplifying the math namespace by getting rid of all the aliases? They're also quite confusing; not sure why `Vec3F` ends with a capital F while `LVector3f` ends with a lower-case f.
Would it be possible to only have `Vec3`, for instance, and let Panda just DTRT or would that be too problematic?

**Comment by rdb** [comment]
Vec3 is a typedef to Vec3F or Vec3D or depending on whether Panda is compiled in double-precision or single-precision floating-point mode.  The API reference generator is not smart enough to realise this, so it simply chooses the single-precision float.  When we switch the API reference to Sphinx format, we might be able to fix this.

It is really important that we offer both single-precision and double-precision types in any case; the difference in performance between them is substantial, and some uses may require different levels of precision.  What compiling Panda in double- or single-precision mode does is that it changes the default, essentially, as well as what Panda accepts and uses in anything that deals with transformations.

The underlying C++ name is LVector3, which is a typedef to LVector3f or LVector3d.  We started offering these when we decided that types should always be available under the C++ name.  I agree that this is unfortunate, but people seem to be opposed to removing the convenient, older `Vec3` alias.  Perhaps we should simply be renaming the C++ types as well.

Normally, you should use Vec3/LVector3, and `add_data3`, which will always choose the right type depending on how Panda is compiled, so that you don't need to worry about this.  So, it is generally a mistake to use `add_data3f` unless you have specific reasons to call it (such as if you are passing in a Vec3F).  I might agree with you that this is unnecessarily convoluted on the user's part; I think I would agree that we shouldn't have add_data3f and add_data3d, but rather that add_data3 should be appropriately overloaded to choose the right variant depending on what the user passes in.  I think this may have not been done in the first place because these methods are usually called in sensitive inner loops and the extra check might make it a bit slower, but it could be argued that people who want to optimize writing vertex data should be using the buffer protocol anyway.

**Comment by Epihaius** [comment]
Ah, it all makes sense now! My apologies for the confusion! The manual page `Creating and filling a GeomVertexData` makes use of `addData3f` in its example and that's where I picked up the habit of using it I guess.

> it could be argued that people who want to optimize writing vertex data should be using the buffer protocol anyway.

Wait, are you referring to copying data between GVAD's using memoryviews or do you mean it's also possible to add new data to a GVAD using a memoryview instead of using a GeomVertexWriter?

**Comment by rdb** [comment]
Ah, okay.  The manual page needs to be fixed, then.

Yes, it's possible to add new data to a GVAD using a memoryview, but you can't change the size while there is a memoryview of that GVAD active, so you first need to explicitly set the number of rows on the GVD before you fill in the newly added rows.

It's harder to get this right, since you need to understand the exact layout of the data yourself, but it can certainly be more efficient.

**Comment by Epihaius** [comment]
Hmm, I was actually wondering about how to get e.g. position data into a vertex column; I guess I'd need to convert the position vector to a bytes object, but I'm not clear on how to do that.

**Comment by rdb** [comment]
Either using the `struct` Python module, or by casting the array to float using something like `memview.cast('B').cast('f')` (requires Python 3) so that you can address it as an array of floats instead of an arroy of bytes.

**Comment by Epihaius** [comment]
Even then I get a TypeError, saying that a bytes-like object is required, not float, when trying to assign a float value to a memoryview slice, e.g.:

```
vertex_format = GeomVertexFormat.get_v3()
vertex_data = GeomVertexData("geom", vertex_format, Geom.UH_static)
vertex_data.set_num_rows(1)
array = vertex_data.modify_array(0)
size = array.data_size_bytes // 4
memview = memoryview(array).cast('B').cast('f')
# attempt to add X-coordinate with value 2.0 to memoryview
memview[:size//3] = 2.  # this causes a TypeError
```

Casting a float to bytes doesn't work either, so I'm not really sure how to do this.

**Comment by rdb** [comment]
Hmm, yeah, that's awkward.  You can update individual values that way:
```python
memview[0] = 2.0
```
But when assigning ranges, you apparently can't use a tuple, but need something also supporting the buffer protocol:
```python
memview[:size//3] = array.array('f', (2.,))
```
But at that point you can also cast to straight byte and use struct:
```python
memview[:16] = struct.pack('ffff', 1.0, 2.0, 3.0, 4.0)
```

All in all, not sure if this is actually better; I've used it with success in the past, but YMMV.

**Comment by Epihaius** [comment]
Thanks!! I'll see how I can use this.

**Comment by Epihaius** [comment]
Commit e9791d7 should fix this issue. Let me know if there are still problems with this.

**Comment by pmp-p** [comment]
looks good
