### ISSUE TITLE
Python 3.x support and UI backend

### ISSUE THREAD

**Issue by Aareon** [Epihaius/panda3dstudio#6]
Hi, I'm curious as to specifically what minor versions of Python you are targeting?

Also, have you any plans of providing alternatives for the wxPython UI backend? Haven't quite scoured through the source enough to see what exactly you'd need out of the UI, but I can say that I've had really good experiences with Tkinter. PyQT5/PySide2 are also good options, though I have less experience with those.

**Comment by Epihaius** [comment]
> Hi, I'm curious as to specifically what minor versions of Python you are targeting?

As it is currently, my project should run on all Python 3 versions supported by Panda3D 1.10 and 1.11, I believe (i.e. 3.5, 3.6 and 3.7).
It is however possible that at some point I might want to use a relative new Python feature, so I would nevertheless advise to always use the newest Python version usable by Panda3D (3.7 at this moment).

> Also, have you any plans of providing alternatives for the wxPython UI backend? Haven't quite scoured through the source enough to see what exactly you'd need out of the UI, but I can say that I've had really good experiences with Tkinter. PyQT5/PySide2 are also good options, though I have less experience with those.

Having experienced all the trouble with trying to make wxPython behave the way I wanted it to (and still not quite succeeding, which is why I kicked it out) and having spent all that time and effort to create my very own pure-Panda3D GUI framework from scratch, I really don't feel like supporting third-party GUI libraries anymore, hope you can understand.
My own framework might still need some work, but at least it looks and feels exactly the way I want it to, it's skinnable, portable (since it's just Panda3D) and it avoids an additional dependency.
As for what I need out of a GUI, in a lot of cases I did need to override standard widget behaviour in wxPython, so I needed to resort to custom widgets anyway - and even that didn't always turn out that great.
Another big problem was handling mouse and keyboard input; sometimes these input events were processed by wxPython and it was hard to make it pass on these events to Panda3D.

So while I'd understand if you didn't feel comfortable with an unfamiliar GUI, even if you would volunteer to assist in making my project work with an external GUI toolkit, I fear it would be a wasted effort.
But if you have some specific grievances concerning my GUI, do let me know and perhaps I can make it better.

**Comment by Aareon** [comment]
I have no qualms personally with wxPython. It does what its supposed to do. Just trying to get a feel of the project.

As for the first question, I'm just trying to see what the minimum target version is so I know what is and is not a viable change in the project. Such as f-strings.

**Comment by Epihaius** [comment]
Fair enough. The minimum target version would be 3.7 then; this is the default version of Python shipped with the installer of Panda3D on Windows anyway, as its developers also want to encourage new users to adopt the latest version.

**Comment by Aareon** [comment]
I am all for that! Thank you :smile:

**Comment by Epihaius** [comment]
No problem :) .

Closing this issue then.
